esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "maxmilo.mitsubishi-hvac"
    version: "1.0.0"

dashboard_import:
  package_import_url: github://zefr0g/maxmilo/example.yaml

logger:
  hardware_uart: UART1
  level: INFO

api:

ota:
  - platform: esphome

web_server:
  port: 80

# Champ texte pour que le client puisse renommer son unité (stocké en mémoire flash)
text:
  - platform: template
    name: "Nom de l'unité"
    id: custom_device_name
    optimistic: true
    restore_value: true
    initial_value: "maxmilo"
    mode: text
